//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentExtractor.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentExtractor.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; is not well-formed URI string.
        /// </summary>
        internal static string BadUri {
            get {
                return ResourceManager.GetString("BadUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load template from file {0}.
        /// </summary>
        internal static string CantLoadTemplate {
            get {
                return ResourceManager.GetString("CantLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save content to file {0}.
        /// </summary>
        internal static string CantSaveFile {
            get {
                return ResourceManager.GetString("CantSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has been successfully saved.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebExtractor console utility
        ///  usage: WebExtractor.Console.exe templateFile [-input url1 url2 ...] [-Excel excelFileName] [-Xml xmlFileName] [-Html htmlFileName]
        ///      templateFile  - path to template you made by WebExtractor 
        ///      url1, url2    - list of source URLs
        ///      
        ///      At least one export file names should be provided
        ///      excelFlieName - path to result in Excel. File will be owerwritten if exist
        ///      xmlFileName   - path to result in Xml. File will be owerwritten if exist
        ///      htmlFi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading pages ....
        /// </summary>
        internal static string LoadingPages {
            get {
                return ResourceManager.GetString("LoadingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export file name for method {0} has been specified.
        /// </summary>
        internal static string NoExportFilename {
            get {
                return ResourceManager.GetString("NoExportFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No export file names have been provided.
        /// </summary>
        internal static string NoExportFiles {
            get {
                return ResourceManager.GetString("NoExportFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t locate template file in {0}.
        /// </summary>
        internal static string TemplateDoesntExist {
            get {
                return ResourceManager.GetString("TemplateDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameters specifier {0}.
        /// </summary>
        internal static string UnknownSpecifier {
            get {
                return ResourceManager.GetString("UnknownSpecifier", resourceCulture);
            }
        }
    }
}
