//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentExtractor.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContentExtractor.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load given document: {0}\r\n{1}.
        /// </summary>
        internal static string CannotLoadDocumentError {
            get {
                return ResourceManager.GetString("CannotLoadDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform transformation using template: {0}\r\n{1}.
        /// </summary>
        internal static string CannotPerformTransformationError {
            get {
                return ResourceManager.GetString("CannotPerformTransformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save result to file {0}\r\n{1}.
        /// </summary>
        internal static string CannotSaveResult {
            get {
                return ResourceManager.GetString("CannotSaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No documents with address &apos;{0}&apos; were found..
        /// </summary>
        internal static string CantParseDocumentAddressWarn {
            get {
                return ResourceManager.GetString("CantParseDocumentAddressWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies specified template and saves resulting data
        ///Usage:
        ///  ContentExtractor.Console.exe &lt;template file&gt; &lt;output&gt; [&lt;urls list&gt;]
        ///
        ///  &lt;template file&gt; - The &quot;.cet&quot; file you created with Content Extractor Gui
        ///  &lt;output&gt; - The destination file where the resulting XML will be stored.
        ///  &lt;urls list&gt; (optional) - a comma separated list of urls or files. 
        ///    Files can be provided using a mask.
        ///
        ///Examples:
        ///&gt; ContentExtractor.Console template1.cet output.xml
        ///      Applies &quot;template1.cet&quot; to urls saved in the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to process document {0}.
        /// </summary>
        internal static string StartProcessDocumentInfo {
            get {
                return ResourceManager.GetString("StartProcessDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template &apos;{0}&apos; cannot be parsed.
        /// </summary>
        internal static string TemplateCannotBeParsedError {
            get {
                return ResourceManager.GetString("TemplateCannotBeParsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be parsed as URLs of file names.
        /// </summary>
        internal static string UrlsOrFilesCannotBeParsedError {
            get {
                return ResourceManager.GetString("UrlsOrFilesCannotBeParsedError", resourceCulture);
            }
        }
    }
}
