//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExtractor_Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebExtractor_Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;3DNews: Casio XD-SW4800: профессиональный карманный полиглот&lt;/title&gt;
        ///    &lt;meta content=&quot;Casio XD-SW4800 переводчик&quot; name=&quot;Keywords&quot; /&gt;
        ///    &lt;meta content=&quot;&quot; name=&quot;Description&quot; /&gt;
        ///    &lt;link href=&quot;/favicon.ico&quot; rel=&quot;SHORTCUT ICON&quot; /&gt;
        ///    &lt;link href=&quot;/default.css&quot; TYPE=&quot;text/css&quot; REL=&quot;stylesheet&quot; /&gt;
        ///    &lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; title=&quot;RSS&quot; href=&quot;http://3dnews.ru/&quot; /&gt;
        ///    &lt;meta name=&quot;Copyright&quot; content=&quot;(C) 1997-2007, 3DNews&quot; /&gt;
        ///    &lt;meta name=&quot;Classifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Best3DNews {
            get {
                return ResourceManager.GetString("Best3DNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Какой подарок самый лучший, или что подарить имениннику? - подарок цветы праздник&lt;/title&gt;
        ///    &lt;link rel=&quot;SHORTCUT ICON&quot; href=&quot;http://www.myjane.ru/favicon.ico&quot; /&gt;
        ///    &lt;META NAME=&quot;author&quot; CONTENT=&quot;@IvLIM 2002-2006 ivlim@ivlim.ru&quot; /&gt;
        ///    &lt;META HTTP-EQUIV=&quot;Content-Style-Type&quot; CONTENT=&quot;text/css&quot; /&gt;
        ///    &lt;META NAME=&quot;ROBOTS&quot; CONTENT=&quot;ALL&quot; /&gt;
        ///    &lt;META NAME=&quot;DESCRIPTION&quot; CONTENT=&quot;подарок цветы праздник&quot; /&gt;
        ///    &lt;META NAME=&quot;KEYWORDS&quot; CONTENT=&quot;подарок цветы праздник&quot; /&gt;
        ///    &lt;LINK hr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BestMyJane {
            get {
                return ResourceManager.GetString("BestMyJane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Test page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;p&gt;
        ///    There is some text!&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string BuildTreeTest {
            get {
                return ResourceManager.GetString("BuildTreeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Test page&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;p&gt;There is some text!&lt;/p&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///
        ///.
        /// </summary>
        internal static string BuildTreeTestResult {
            get {
                return ResourceManager.GetString("BuildTreeTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Free Software Downloads and Software Reviews - Download.com&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;Find the software you&apos;re looking for at Download.com, the most comprehensive source for free-to-try software downloads on the Web. Includes audio programs, utilities, Internet and desktop software, applications for developers, downloads for small business users, and more.&quot; /&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;download, utilities, windo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string download_com {
            get {
                return ResourceManager.GetString("download_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1251&quot;&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;/cifrovik/themes/default/css/default.css&quot; type=&quot;text/css&quot;&gt;
        ///  &lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot;&gt;
        ///  &lt;title&gt;CECT IP1000 - &quot;цветы&quot; распускаются зимой&lt;/title&gt;
        ///  &lt;meta name=&quot;description&quot; content=&quot;CECT IP1000 - &amp;quot;цветы&amp;quot; распускаются зимой&quot;&gt;
        ///  &lt;meta name=&quot;keywords&quot; content=&quot;CECT IP1000 - &amp;quot;цветы&amp;quot; распускаются зимой&quot;&gt;
        ///  &lt;script src=&quot;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoadHtmlTest1 {
            get {
                return ResourceManager.GetString("LoadHtmlTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1251&quot;?&gt;
        ///&lt;html&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string mambo {
            get {
                return ResourceManager.GetString("mambo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;Энциклопедия кино - награды и номинации премий и кинофестивалей: Ника - 2004&lt;/title&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1251&quot;&gt;&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;ru&quot;&gt;&lt;META name=&quot;Description&quot; content=&quot;Энциклопедия кино: награды и номинации премий и кинофестивалей, Ника - 2004&quot;&gt;&lt;META name=&quot;Keywords&quot; content=&quot;энциклопедия, кино, фильм, награда, номинация, премия, кинофестиваль, фестиваль, Ника - 2004&quot;&gt;&lt;LINK href=&quot;/styles/main.css&quot; type=&quot;text/css&quot; rel= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NotClosedTags {
            get {
                return ResourceManager.GetString("NotClosedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;A string looks like title&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;table&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;
        ///          There is some text!
        ///        &lt;/td&gt;
        ///        &lt;td&gt;
        ///          2
        ///        &lt;/td&gt;
        ///      &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string TempalteTest1 {
            get {
                return ResourceManager.GetString("TempalteTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Заголовок&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;table border=&quot;0&quot; width=&quot;80%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; class=&quot;search&quot; bgcolor=&quot;#ffcc00&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;form name=&quot;web&quot; method=&quot;get&quot; action=&quot;/yandsearch&quot; class=&quot;search&quot;&gt;
        ///        &lt;input type=&quot;hidden&quot; name=&quot;stype&quot; value=&quot;&quot; /&gt;
        ///        &lt;input type=&quot;hidden&quot; name=&quot;nl&quot; value=&quot;0&quot; /&gt;
        ///        &lt;td width=&quot;99%&quot;&gt;
        ///          &lt;input type=&quot;text&quot; name=&quot;text&quot; value=&quot;&quot; size=&quot;40&quot; style=&quot;width: 100%;&quot; /&gt;
        ///        &lt;/td&gt;
        ///        &lt;td&gt;
        ///          &lt;input type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlNode2HtmlElementTest3 {
            get {
                return ResourceManager.GetString("XmlNode2HtmlElementTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Яндекс&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;div&gt;
        ///    &lt;/div&gt;
        ///    &lt;table&gt;
        ///    &lt;/table&gt;
        ///    &lt;div style=&quot;margin: 0 3%;&quot;&gt;
        ///      &lt;div style=&quot;width: 100%;&quot;&gt;
        ///        &lt;table&gt;
        ///          &lt;tr id=&quot;trToTest&quot;&gt;
        ///            &lt;td&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///            &lt;/td&gt;
        ///            &lt;td&gt;
        ///              &lt;noindex&gt;
        ///                &lt;ol id=&quot;toTest&quot;&gt;
        ///                  &lt;li&gt;Росохранкультура решит &lt;a onclick=&quot;r(this, &apos;mnews&apos;)&quot; href=&quot;http://news.y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlNode2HtmlNode_yandex {
            get {
                return ResourceManager.GetString("XmlNode2HtmlNode_yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;link rel=&quot;SHORTCUT ICON&quot; href=&quot;http://img.yandex.net/i/favicon.ico&quot;&gt;
        ///&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; title=&quot; &quot; href=&quot;http://company.yandex.ru/news/news.rss&quot;&gt;
        ///&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; title=&quot; &quot; href=&quot;http://company.yandex.ru/blog/index.rss&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body, td,
        ///table.home-head td.enter { font-size: 80%; font-family: Arial, &apos;Geneva CY&apos;, sans-serif; }
        ///table.home-head td { font-size: 70%; font-family: Verdana, Arial,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yandex {
            get {
                return ResourceManager.GetString("yandex", resourceCulture);
            }
        }
    }
}
